apiVersion: skaffold/v4beta9
kind: Config

build:
  artifacts:
    - image: us-central1-docker.pkg.dev/gke-project-481520/gke-repo/quickstart-image
    - image: us-central1-docker.pkg.dev/gke-project-481520/gke-repo/flask-image

manifests:
  rawYaml:
    - kubernetes/*.yaml

deploy:
  kubectl: {}
