apiVersion: skaffold/v4beta9
kind: Config

build:
  artifacts:
    - image: us-central1-docker.pkg.dev/gke-project-481520/gke-repo/quickstart-image
    - image: us-central1-docker.pkg.dev/gke-project-481520/gke-repo/flask-image

manifests:
  rawYaml:
    - kubernetes/*.yaml

deploy:
  kubectl: {}

profiles:
  # Profil pour l'environnement de développement (dev)
  - name: dev
    patches:
      # Ajoute le namespace 'dev' par défaut pour les manifestes Kubernetes
      - op: add
        path: /deploy/kubectl/defaultNamespace
        value: dev
  
  # Profil pour l'environnement de production (prod)
  - name: prod
    patches:
      # Ajoute le namespace 'prod' par défaut pour les manifestes Kubernetes
      - op: add
        path: /deploy/kubectl/defaultNamespace
        value: prod
